### ISSUE TITLE
Diretório "get-started"

### ISSUE THREAD

**Issue by that-jpg** [EmberJSBrasil/guides#1]
Eu acabei de traduzir ele, mas não estou conseguindo conectar na Internet à não ser pelo 3g do celular, se alguém quiser traduzir alguma coisa pule os arquivos dessa pasta.

**Comment by that-jpg** [comment]
Os arquivos foram adicionados, se alguem tiver alguma alteração neles é só mandar um pr :)

**Comment by jeanlucaslima** [comment]
Esse já foi revisado?

**Comment by that-jpg** [comment]
Essa issue era só pra avisar quem estivesse querendo traduzir algo não traduzir o mesmo que eu. E eu já commitei essas alterações.

**Comment by jeanlucaslima** [comment]
Mas... E a tradução, foi revisada?
